import { StickerTemplate, StickerLayer } from './types';

export const CATEGORIES = [
  { id: 'all', name: 'Tutti', icon: 'Sparkles' },
  { id: 'amore', name: 'Amore e Affetto', icon: 'Heart' },
  { id: 'reazioni', name: 'Emozioni e Reazioni', icon: 'Smile' },
  { id: 'saluti', name: 'Saluti (Giorno/Notte)', icon: 'Coffee' },
  { id: 'feste', name: 'Feste & Auguri', icon: 'Gift' },
  { id: 'meme', name: 'Meme & Umorismo', icon: 'Laugh' },
  { id: 'lavoro', name: 'Ufficio & Studio', icon: 'Briefcase' }
];

export const FONTS = [
  { id: 'Inter', name: 'Moderno (Inter)' },
  { id: 'Space Grotesk', name: 'Tecnologico (Space Grotesk)' },
  { id: 'Fredoka', name: 'Arrotondato (Fredoka)' },
  { id: 'Pacifico', name: 'Corsivo Elegante (Pacifico)' },
  { id: 'Impact', name: 'Meme Bold (Impact)' },
  { id: 'Comic Sans MS', name: 'Fumetto (Comic Sans)' },
  { id: 'Courier New', name: 'Scritto a Macchina' },
  { id: 'Georgia', name: 'Classico Serif' }
];

export const SHAPES = [
  { id: 'circle', name: 'Cerchio' },
  { id: 'square', name: 'Quadrato' },
  { id: 'heart', name: 'Cuore' },
  { id: 'star', name: 'Stella' },
  { id: 'badge', name: 'Scudetto/Badge' },
  { id: 'cloud', name: 'Nuvola' },
  { id: 'banner', name: 'Nastro/Banner' }
];

export const EMOJI_LIST = [
  // Emozioni
  '😀', '😂', '🤣', '😉', '😊', '😍', '😘', '😋', '😜', '😎', '🤩', '🥳', '🤯', '😡', '😱', '😰', '😴', '🙄', '💀', '🤡',
  // Amore & Cuori
  '❤️', '💖', '💝', '💕', '💘', '💔', '💌', '🌹', '💋',
  // Reazioni & Gestures
  '👍', '👎', '👌', '✌️', '👊', '👏', '🙌', '🙏', '🔥', '✨', '⚡', '💯', '🔔', '🚫', '⚠️', '💡',
  // Cibo & Caffè
  '☕', '🍕', '🍺', '🥤', '🍦', '🍰', '🧁', '🍩',
  // Feste & Varie
  '🎉', '🎈', '🎁', '🎂', '👑', '⭐️', '🌈', '☀️', '🌙', '💻', '💼', '📅', '💤'
];

export const APP_PRES_PALETTES = [
  { name: 'Pop Coral', text: '#ffffff', bg: '#ff4a5a', stroke: '#000000' },
  { name: 'Neon Lime', text: '#000000', bg: '#ccff00', stroke: '#000000' },
  { name: 'Cyan Power', text: '#ffffff', bg: '#06b6d4', stroke: '#0f172a' },
  { name: 'Pastel Lavender', text: '#3c006f', bg: '#e9d5ff', stroke: '#3c006f' },
  { name: 'WhatsApp Gold', text: '#ffffff', bg: '#128c7e', stroke: '#075e54' },
  { name: 'Comic Yellow', text: '#000000', bg: '#facc15', stroke: '#000000' },
  { name: 'Soft Peach', text: '#7c2d12', bg: '#ffedd5', stroke: '#7c2d12' }
];

// High-quality templates that serve as starting points for further editing
export const STICKER_TEMPLATES: StickerTemplate[] = [
  {
    id: 't-amore-1',
    name: 'Cuore Dolce Cupido',
    category: 'amore',
    tags: ['cuore', 'ti amo', 'amore'],
    globalBorder: true,
    layers: [
      {
        id: 'layer-shape-1',
        name: 'Cuore Base',
        type: 'shape',
        shapeType: 'heart',
        x: 256,
        y: 230,
        scale: 1.4,
        rotation: 0,
        opacity: 1,
        visible: true,
        fillColor: '#ef4444',
        strokeColor: '#b91c1c',
        strokeWidth: 4
      },
      {
        id: 'layer-emoji-1',
        name: 'Occhi a Cuore',
        type: 'emoji',
        emoji: '😍',
        x: 256,
        y: 200,
        scale: 1.5,
        rotation: 0,
        opacity: 1,
        visible: true,
        size: 50
      },
      {
        id: 'layer-text-1',
        name: 'Scritta Amore',
        type: 'text',
        text: 'TI AMO!',
        x: 256,
        y: 350,
        scale: 1,
        rotation: -4,
        opacity: 1,
        visible: true,
        fontSize: 38,
        color: '#ffffff',
        fontFamily: 'Fredoka',
        strokeColor: '#7f1d1d',
        strokeWidth: 6,
        bold: true,
        italic: false,
        textAlign: 'center',
        hasShadow: true,
        shadowColor: 'rgba(0,0,0,0.3)'
      }
    ]
  },
  {
    id: 't-amore-2',
    name: 'Nuvola Pensiero',
    category: 'amore',
    tags: ['pensiero', 'love', 'affetto'],
    globalBorder: true,
    layers: [
      {
        id: 'layer-shape-nuvola',
        name: 'Sfondo Nuvola',
        type: 'shape',
        shapeType: 'cloud',
        x: 256,
        y: 240,
        scale: 1.6,
        rotation: 0,
        opacity: 0.95,
        visible: true,
        fillColor: '#fef08a',
        strokeColor: '#ca8a04',
        strokeWidth: 4
      },
      {
        id: 'layer-emoji-cuoricini',
        name: 'Cuori Volanti',
        type: 'emoji',
        emoji: '💖',
        x: 180,
        y: 190,
        scale: 1.2,
        rotation: -15,
        opacity: 1,
        visible: true,
        size: 40
      },
      {
        id: 'layer-emoji-cuoricini2',
        name: 'Cuoricino 2',
        type: 'emoji',
        emoji: '✨',
        x: 320,
        y: 170,
        scale: 1,
        rotation: 12,
        opacity: 1,
        visible: true,
        size: 30
      },
      {
        id: 'layer-text-pensieri',
        name: 'Scritta Pensiero',
        type: 'text',
        text: 'Nei Miei Pensieri',
        x: 256,
        y: 260,
        scale: 1,
        rotation: 2,
        opacity: 1,
        visible: true,
        fontSize: 24,
        color: '#854d0e',
        fontFamily: 'Pacifico',
        strokeColor: '#ffffff',
        strokeWidth: 4,
        bold: false,
        italic: false,
        textAlign: 'center',
        hasShadow: false,
        shadowColor: ''
      }
    ]
  },
  {
    id: 't-meme-1',
    name: 'Meme Alert',
    category: 'meme',
    tags: ['meme', 'divertente', 'panico'],
    globalBorder: true,
    layers: [
      {
        id: 'layer-shape-shield',
        name: 'Scudetto Pericolo',
        type: 'shape',
        shapeType: 'badge',
        x: 256,
        y: 240,
        scale: 1.5,
        rotation: 0,
        opacity: 1,
        visible: true,
        fillColor: '#f97316',
        strokeColor: '#ea580c',
        strokeWidth: 5
      },
      {
        id: 'layer-text-top',
        name: 'Testo Superiore',
        type: 'text',
        text: 'ALLERTA',
        x: 256,
        y: 180,
        scale: 1,
        rotation: 0,
        opacity: 1,
        visible: true,
        fontSize: 34,
        color: '#ffffff',
        fontFamily: 'Space Grotesk',
        strokeColor: '#000000',
        strokeWidth: 7,
        bold: true,
        italic: false,
        textAlign: 'center',
        hasShadow: true,
        shadowColor: 'rgba(0,0,0,0.5)'
      },
      {
        id: 'layer-emoji-warning',
        name: 'Esplosione Emote',
        type: 'emoji',
        emoji: '🤯',
        x: 256,
        y: 270,
        scale: 1.8,
        rotation: 0,
        opacity: 1,
        visible: true,
        size: 55
      },
      {
        id: 'layer-text-bottom',
        name: 'Testo Inferiore',
        type: 'text',
        text: 'DISAGIO!',
        x: 256,
        y: 370,
        scale: 1,
        rotation: 5,
        opacity: 1,
        visible: true,
        fontSize: 38,
        color: '#facc15',
        fontFamily: 'Impact',
        strokeColor: '#000000',
        strokeWidth: 8,
        bold: true,
        italic: false,
        textAlign: 'center',
        hasShadow: true,
        shadowColor: 'rgba(0,0,0,0.5)'
      }
    ]
  },
  {
    id: 't-meme-2',
    name: 'Anche No Ribbon',
    category: 'meme',
    tags: ['ironico', 'no', 'lavoro'],
    globalBorder: true,
    layers: [
      {
        id: 'layer-shape-banner',
        name: 'Fascia Nastro',
        type: 'shape',
        shapeType: 'banner',
        x: 256,
        y: 250,
        scaleX: 1.7,
        scaleY: 0.9,
        scale: 1.3,
        rotation: -5,
        opacity: 1,
        visible: true,
        fillColor: '#06b6d4',
        strokeColor: '#0891b2',
        strokeWidth: 4
      },
      {
        id: 'layer-emoji-thumb',
        name: 'Dito Giù',
        type: 'emoji',
        emoji: '👎',
        x: 256,
        y: 151,
        scale: 1.4,
        rotation: 12,
        opacity: 1,
        visible: true,
        size: 45
      },
      {
        id: 'layer-text-ribbon',
        name: 'Scritta No',
        type: 'text',
        text: 'ANCHE NO.',
        x: 256,
        y: 285,
        scale: 1,
        rotation: -5,
        opacity: 1,
        visible: true,
        fontSize: 32,
        color: '#ffffff',
        fontFamily: 'Impact',
        strokeColor: '#091e3a',
        strokeWidth: 6,
        bold: true,
        italic: false,
        textAlign: 'center',
        hasShadow: true,
        shadowColor: 'rgba(0,0,0,0.3)'
      }
    ]
  },
  {
    id: 't-saluti-1',
    name: 'Buongiorno Energico',
    category: 'saluti',
    tags: ['buongiorno', 'sole', 'saluti', 'caffe'],
    globalBorder: true,
    layers: [
      {
        id: 'layer-shape-sun',
        name: 'Sole di Sfondo',
        type: 'shape',
        shapeType: 'circle',
        x: 256,
        y: 220,
        scale: 1.4,
        rotation: 0,
        opacity: 1,
        visible: true,
        fillColor: '#fef08a',
        strokeColor: '#facc15',
        strokeWidth: 3
      },
      {
        id: 'layer-emoji-coffee',
        name: 'Tazzina Caffè',
        type: 'emoji',
        emoji: '☕',
        x: 256,
        y: 200,
        scale: 1.8,
        rotation: -10,
        opacity: 1,
        visible: true,
        size: 60
      },
      {
        id: 'layer-text-bg',
        name: 'Scritta Giorno',
        type: 'text',
        text: 'Buongiorno!',
        x: 256,
        y: 335,
        scale: 1,
        rotation: -2,
        opacity: 1,
        visible: true,
        fontSize: 36,
        color: '#1e293b',
        fontFamily: 'Space Grotesk',
        strokeColor: '#ffffff',
        strokeWidth: 8,
        bold: true,
        italic: false,
        textAlign: 'center',
        hasShadow: true,
        shadowColor: 'rgba(0,0,0,0.15)'
      },
      {
        id: 'layer-emoji-sunshine',
        name: 'Raggi Splendenti',
        type: 'emoji',
        emoji: '✨',
        x: 340,
        y: 140,
        scale: 1,
        rotation: 15,
        opacity: 1,
        visible: true,
        size: 30
      }
    ]
  },
  {
    id: 't-saluti-2',
    name: 'Buonanotte Sognante',
    category: 'saluti',
    tags: ['notte', 'buonanotte', 'stelle', 'sonno'],
    globalBorder: true,
    layers: [
      {
        id: 'layer-shape-moon',
        name: 'Nuvola Scura',
        type: 'shape',
        shapeType: 'cloud',
        x: 256,
        y: 232,
        scale: 1.5,
        rotation: 0,
        opacity: 1,
        visible: true,
        fillColor: '#1e1b4b',
        strokeColor: '#312e81',
        strokeWidth: 4
      },
      {
        id: 'layer-emoji-moon-notte',
        name: 'Luna',
        type: 'emoji',
        emoji: '🌙',
        x: 220,
        y: 190,
        scale: 1.5,
        rotation: -20,
        opacity: 1,
        visible: true,
        size: 50
      },
      {
        id: 'layer-emoji-stars',
        name: 'Zzz',
        type: 'emoji',
        emoji: '💤',
        x: 300,
        y: 170,
        scale: 1,
        rotation: 10,
        opacity: 1,
        visible: true,
        size: 35
      },
      {
        id: 'layer-text-notte-scritta',
        name: 'Testo Notte',
        type: 'text',
        text: 'Sogni d\'Oro ✨',
        x: 256,
        y: 290,
        scale: 1,
        rotation: 0,
        opacity: 1,
        visible: true,
        fontSize: 28,
        color: '#fef08a',
        fontFamily: 'Pacifico',
        strokeColor: '#1e1b4b',
        strokeWidth: 4,
        bold: false,
        italic: false,
        textAlign: 'center',
        hasShadow: true,
        shadowColor: 'rgba(0,0,0,1)'
      }
    ]
  },
  {
    id: 't-feste-1',
    name: 'Auguri Esplosivi',
    category: 'feste',
    tags: ['compleanno', 'auguri', 'festa'],
    globalBorder: true,
    layers: [
      {
        id: 'layer-shape-festarolo',
        name: 'Badge Circolare',
        type: 'shape',
        shapeType: 'circle',
        x: 256,
        y: 240,
        scale: 1.5,
        rotation: 0,
        opacity: 1,
        visible: true,
        fillColor: '#ec4899',
        strokeColor: '#ffffff',
        strokeWidth: 5
      },
      {
        id: 'layer-emoji-torta',
        name: 'Torta del festeggiato',
        type: 'emoji',
        emoji: '🎂',
        x: 256,
        y: 190,
        scale: 1.8,
        rotation: 0,
        opacity: 1,
        visible: true,
        size: 60
      },
      {
        id: 'layer-text-auguri',
        name: 'Scritta Auguri',
        type: 'text',
        text: 'AUGURI! 🎉',
        x: 256,
        y: 310,
        scale: 1,
        rotation: -4,
        opacity: 1,
        visible: true,
        fontSize: 34,
        color: '#ffffff',
        fontFamily: 'Fredoka',
        strokeColor: '#9d174d',
        strokeWidth: 6,
        bold: true,
        italic: false,
        textAlign: 'center',
        hasShadow: true,
        shadowColor: 'rgba(0,0,0,0.35)'
      }
    ]
  },
  {
    id: 't-reazioni-1',
    name: 'Molto Bene OK',
    category: 'reazioni',
    tags: ['approvato', 'ok', 'grande', 'pollice'],
    globalBorder: true,
    layers: [
      {
        id: 'layer-shape-approvato',
        name: 'Stella Sfondo',
        type: 'shape',
        shapeType: 'star',
        x: 256,
        y: 236,
        scale: 1.6,
        rotation: 12,
        opacity: 0.95,
        visible: true,
        fillColor: '#22c55e',
        strokeColor: '#16a34a',
        strokeWidth: 4
      },
      {
        id: 'layer-emoji-pollice',
        name: 'Mano di Successo',
        type: 'emoji',
        emoji: '👌',
        x: 256,
        y: 200,
        scale: 1.6,
        rotation: -12,
        opacity: 1,
        visible: true,
        size: 55
      },
      {
        id: 'layer-text-grandioso',
        name: 'Scritta Approvato',
        type: 'text',
        text: 'GRANDIOSO!',
        x: 256,
        y: 330,
        scale: 1,
        rotation: 0,
        opacity: 1,
        visible: true,
        fontSize: 28,
        color: '#ffffff',
        fontFamily: 'Space Grotesk',
        strokeColor: '#14532d',
        strokeWidth: 6,
        bold: true,
        italic: false,
        textAlign: 'center',
        hasShadow: true,
        shadowColor: 'rgba(0,0,0,0.3)'
      }
    ]
  },
  {
    id: 't-lavoro-1',
    name: 'Disperazione Lunedì',
    category: 'lavoro',
    tags: ['lavoro', 'ufficio', 'lunedi', 'caffe'],
    globalBorder: true,
    layers: [
      {
        id: 'layer-shape-lavoro-back',
        name: 'Sfondo Rettangolo',
        type: 'shape',
        shapeType: 'square',
        x: 256,
        y: 250,
        scaleX: 1.5,
        scaleY: 1,
        scale: 1.4,
        rotation: 4,
        opacity: 1,
        visible: true,
        fillColor: '#374151',
        strokeColor: '#1f2937',
        strokeWidth: 5
      },
      {
        id: 'layer-text-lavoro-1',
        name: 'Scritta Noia',
        type: 'text',
        text: 'MAI UNA GIOIA',
        x: 256,
        y: 190,
        scale: 1,
        rotation: 4,
        opacity: 1,
        visible: true,
        fontSize: 26,
        color: '#ef4444',
        fontFamily: 'Impact',
        strokeColor: '#ffffff',
        strokeWidth: 5,
        bold: true,
        italic: false,
        textAlign: 'center',
        hasShadow: true,
        shadowColor: 'rgba(0,0,0,0.5)'
      },
      {
        id: 'layer-emoji-lavoro-batteria',
        name: 'Batteria Scarica',
        type: 'emoji',
        emoji: '🔋',
        x: 256,
        y: 280,
        scale: 1.3,
        rotation: -4,
        opacity: 1,
        visible: true,
        size: 40
      },
      {
        id: 'layer-text-lavoro-2',
        name: 'Scritta Ufficio',
        type: 'text',
        text: 'In Ufficio 😴',
        x: 256,
        y: 350,
        scale: 1,
        rotation: 4,
        opacity: 1,
        visible: true,
        fontSize: 22,
        color: '#e5e7eb',
        fontFamily: 'Space Grotesk',
        strokeColor: '#111827',
        strokeWidth: 4,
        bold: true,
        italic: false,
        textAlign: 'center',
        hasShadow: true,
        shadowColor: 'rgba(0,0,0,0.5)'
      }
    ]
  }
];
